# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
