# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
